export const temas = [
    "el examen de cazador",
    "la torre celestial",
    "la ciudad de Yorknew",
    "la Brigada Fantasma",
    "Greed Island",
    "el arco de las Hormigas Quimera",
    "la expedición al Continente Oscuro",
    "la sucesión al trono de Kakin",
    "la mafia de Yorknew",
    "la familia Zoldyck",
    "Gon Freecss",
    "Killua Zoldyck",
    "Kurapika",
    "Leorio",
    "Hisoka",
    "Chrollo Lucilfer",
    "Meruem",
    "Netero",
    "Biscuit Krueger",
    "Illumi Zoldyck",
    "Silva Zoldyck",
    "Zeno Zoldyck",
    "Feitan",
    "Phinks",
    "Shizuku",
    "Machi",
    "Kortopi",
    "Pitou",
    "Youpi",
    "Pouf",
    "poderes y tipos de Nen",
    "las categorías del Nen",
    "el Hatsu",
    "las restricciones y contratos del Nen",
    "los examinadores del examen de cazador",
    "las licencias de cazador",
    "los juegos en Greed Island",
    "la Asociación de Cazadores",
    "los Zodiacos de Netero",
    "las cartas de Greed Island",
    "las habilidades de cada miembro de la Brigada Fantasma",
    "las habilidades de los miembros de la Guardia Real",
    "los diferentes tipos de aura",
    "las pruebas dentro de la torre celestial",
    "las motivaciones de los personajes",
    "los momentos más importantes de Gon",
    "la evolución de Killua",
    "los conflictos entre Kurapika y la araña",
    "la filosofía de Meruem",
    "momentos icónicos de la serie"
];
